# Generated by Django 2.1.3 on 2018-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esma', '0010_auto_20181023_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtratingcreatedata',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reportingtypeinfo',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
