# Generated by Django 2.1.3 on 2019-01-21 10:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('esma', '0011_auto_20181112_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfile',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
