# Generated by Django 2.1.3 on 2018-11-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0008_auto_20181109_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardingprocess',
            old_name='enagement_letter_signed',
            new_name='engagement_letter_signed',
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='date_time_engagement_letter_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='date_time_onboarding_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='instrument_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='issuer_long_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='issuer_short_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprocess',
            name='target_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='relationship_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_manager_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
