# Generated by Django 2.1.3 on 2019-01-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0009_auto_20181112_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_free_text', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='issuer.Issuer')),
            ],
        ),
    ]
