# Generated by Django 2.1.3 on 2018-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20181025_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seniority',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='historicalissue',
            name='name',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
    ]
