# Generated by Django 2.1.3 on 2019-01-03 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuer', '0009_auto_20181112_1512'),
        ('rating_process', '0013_issuedecisionattribute_is_between_committees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('date_time_deleted', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_time_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_time_approval', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assessment_lt', models.IntegerField(blank=True, choices=[(1, 'aaa'), (2, 'aa+'), (3, 'aa'), (4, 'aa-'), (5, 'a+'), (6, 'a'), (7, 'a-'), (8, 'bbb+'), (9, 'bbb'), (10, 'bbb-'), (11, 'bb+'), (12, 'bb'), (13, 'bb-'), (14, 'b+'), (15, 'b'), (16, 'b-'), (17, 'ccc'), (18, 'cc'), (19, 'c'), (20, 'd'), (21, 'sd'), (200, 'nr')], null=True)),
                ('comment', tinymce.models.HTMLField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_approved_by', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_initiated_by', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issuer.Issuer')),
                ('previous_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credit_assessment.AssessmentJob')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSubscoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_edit_allowed', models.BooleanField(default=False)),
                ('decided_score', models.IntegerField(blank=True, choices=[(1, 'aa'), (2, 'aa-'), (3, 'a+'), (4, 'a'), (5, 'a-'), (6, 'bbb+'), (7, 'bbb'), (8, 'bbb-'), (9, 'bb+'), (10, 'bb'), (11, 'bb-'), (12, 'b+'), (13, 'b'), (14, 'b-'), (None, 'n/a')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('decided_notch_adjustment', models.IntegerField(blank=True, choices=[(5, '+5'), (4, '+4'), (3, '+3'), (2, '+2'), (1, '+1'), (0, '0'), (-1, '-1'), (-2, '-2'), (-3, '-3'), (-4, '-4'), (-5, '-5')], default=None, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_assessment.AssessmentJob')),
                ('subfactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rating_process.InternalScoreDataSubfactor')),
            ],
            options={
                'ordering': ['assessment__issuer', 'assessment', 'subfactor__factor', 'subfactor'],
            },
        ),
    ]
