# Generated by Django 2.1.3 on 2019-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentjob',
            options={'ordering': ['issuer', 'date_time_creation']},
        ),
        migrations.AddField(
            model_name='assessmentjob',
            name='process_step',
            field=models.IntegerField(choices=[(1, 'setup'), (2, 'pre_committee'), (3, 'analytical_phase'), (4, 'post_committee'), (5, 'editor_phase'), (6, 'issuer_confirmation_phase'), (7, 'analyst_final_approval_phase'), (8, 'chair_final_approval_phase'), (9, 'publishing_phase'), (10, 'publishing_phase_done')], db_index=True, default=1),
        ),
    ]
