# Generated by Django 2.1.3 on 2019-01-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20181121_1735'),
        ('credit_assessment', '0002_auto_20190104_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorityLevelAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_lt', models.IntegerField(blank=True, choices=[(1, 'aaa'), (2, 'aa+'), (3, 'aa'), (4, 'aa-'), (5, 'a+'), (6, 'a'), (7, 'a-'), (8, 'bbb+'), (9, 'bbb'), (10, 'bbb-'), (11, 'bb+'), (12, 'bb'), (13, 'bb-'), (14, 'b+'), (15, 'b'), (16, 'b-'), (17, 'ccc'), (18, 'cc'), (19, 'c'), (20, 'd'), (21, 'sd'), (200, 'nr')], null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_assessment.AssessmentJob')),
                ('seniority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issue.Seniority')),
            ],
            options={
                'ordering': ['assessment__issuer', 'assessment__date_time_creation', 'seniority'],
            },
        ),
    ]
