# Generated by Django 2.1.3 on 2019-01-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_assessment', '0003_senioritylevelassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestLowest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_aaa', models.BooleanField(default=False)),
                ('is_aa_plus', models.BooleanField(default=False)),
                ('is_ccc', models.BooleanField(default=False)),
                ('is_cc', models.BooleanField(default=False)),
                ('is_c', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='credit_assessment.AssessmentJob')),
            ],
            options={
                'ordering': ['assessment__issuer', 'assessment__date_time_creation', 'pk'],
            },
        ),
    ]
