# Generated by Django 2.1.3 on 2018-11-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating_process', '0010_auto_20181122_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissuedecision',
            name='process_step',
            field=models.IntegerField(choices=[(1, 'setup'), (2, 'pre_committee'), (3, 'analytical_phase'), (4, 'post_committee'), (5, 'editor_phase'), (6, 'issuer_confirmation_phase'), (7, 'analyst_final_approval_phase'), (8, 'chair_final_approval_phase'), (9, 'publishing_phase'), (10, 'publishing_phase_done')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='historicalissuedecision',
            name='proposed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedecision',
            name='process_step',
            field=models.IntegerField(choices=[(1, 'setup'), (2, 'pre_committee'), (3, 'analytical_phase'), (4, 'post_committee'), (5, 'editor_phase'), (6, 'issuer_confirmation_phase'), (7, 'analyst_final_approval_phase'), (8, 'chair_final_approval_phase'), (9, 'publishing_phase'), (10, 'publishing_phase_done')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='issuedecision',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_decision_proposed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuedecision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_decision_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
