# Generated by Django 2.1.3 on 2018-12-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_process', '0011_auto_20181130_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalissuedecision',
            old_name='approved_by',
            new_name='chair',
        ),
        migrations.RenameField(
            model_name='issuedecision',
            old_name='approved_by',
            new_name='chair',
        ),
    ]
