# Generated by Django 2.1.3 on 2018-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_process', '0012_auto_20181203_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedecisionattribute',
            name='is_between_committees',
            field=models.BooleanField(default=False),
        ),
    ]
